version: "3"
services:
  elasticsearch:
    container_name: techmaster-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    volumes:
      - ./data:/usr/share/elasticsearch/data