version: "3"
services:
  elasticsearch:
    container_name: techmaster-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - xpack.security.enabled=false 
      - discovery.type=single-node
    mem_limit: 1073741824
    ports:
      - 9200:9200
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
volumes:
  data-elasticsearch:
    driver: local